# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Number of days of inactivity before an Issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before an Issue with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 30

# Issues with these labels will never be considered stale. Set to `[]` to disable
# We don't close any issue that is an enhancement or confirmed bug, but issues
# waiting for reproduction cases and questions tend to get outdated.
exemptLabels:
  - "enhancement"
  - "bug"
  - "thinking"
  - "docs"

# Label to use when marking as stale
staleLabel: "waiting-reply"

# Comment to post when marking as stale. Set to `false` to disable
markComment: |
  Hey there,
  We wanted to check in on this request since it has been inactive for at least 90 days.
  Have you reviewed the latest [godocs](https://godoc.org/github.com/hashicorp/raft)? 
  If you think this is still an important issue in the latest version of [the Raft library](https://github.com/hashicorp/raft/compare/) or 
  [its documentation](https://github.com/hashicorp/raft/compare/) please feel let us know and we'll keep it open for investigation.
  If there is still no activity on this request in 30 days, we will go ahead and close it.
  Thank you!

# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false

# Comment to post when closing a stale Issue. Set to `false` to disable
closeComment: >
  Hey there,
  This issue has been automatically closed because there hasn't been any activity for a while. 
  If you are still experiencing problems, or still have questions, feel free to [open a new one](https://github.com/hashicorp/raft/issues/new) :+1
