// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package raft

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufAppendEntriesRequest = []byte{135}

func (t *AppendEntriesRequest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufAppendEntriesRequest); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.Leader ([]uint8) (slice)
	if len(t.Leader) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Leader was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Leader))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Leader); err != nil {
		return err
	}

	// t.PrevLogEntry (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.PrevLogEntry)); err != nil {
		return err
	}

	// t.PrevLogTerm (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.PrevLogTerm)); err != nil {
		return err
	}

	// t.Entries ([]*raft.Log) (slice)
	if len(t.Entries) > 8192 {
		return xerrors.Errorf("Slice value in field t.Entries was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Entries))); err != nil {
		return err
	}
	for _, v := range t.Entries {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}

	// t.LeaderCommitIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LeaderCommitIndex)); err != nil {
		return err
	}

	return nil
}

func (t *AppendEntriesRequest) UnmarshalCBOR(r io.Reader) (err error) {
	*t = AppendEntriesRequest{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 7 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.Leader ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Leader: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Leader = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Leader); err != nil {
		return err
	}

	// t.PrevLogEntry (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.PrevLogEntry = uint64(extra)

	}
	// t.PrevLogTerm (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.PrevLogTerm = uint64(extra)

	}
	// t.Entries ([]*raft.Log) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Entries: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Entries = make([]*Log, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.Entries[i] = new(Log)
					if err := t.Entries[i].UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.Entries[i] pointer: %w", err)
					}
				}

			}

		}
	}
	// t.LeaderCommitIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LeaderCommitIndex = uint64(extra)

	}
	return nil
}

var lengthBufAppendEntriesResponse = []byte{133}

func (t *AppendEntriesResponse) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufAppendEntriesResponse); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.LastLog (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LastLog)); err != nil {
		return err
	}

	// t.Success (bool) (bool)
	if err := cbg.WriteBool(w, t.Success); err != nil {
		return err
	}

	// t.NoRetryBackoff (bool) (bool)
	if err := cbg.WriteBool(w, t.NoRetryBackoff); err != nil {
		return err
	}
	return nil
}

func (t *AppendEntriesResponse) UnmarshalCBOR(r io.Reader) (err error) {
	*t = AppendEntriesResponse{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 5 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.LastLog (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LastLog = uint64(extra)

	}
	// t.Success (bool) (bool)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.Success = false
	case 21:
		t.Success = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	// t.NoRetryBackoff (bool) (bool)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.NoRetryBackoff = false
	case 21:
		t.NoRetryBackoff = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufRequestVoteRequest = []byte{134}

func (t *RequestVoteRequest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufRequestVoteRequest); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.Candidate ([]uint8) (slice)
	if len(t.Candidate) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Candidate was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Candidate))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Candidate); err != nil {
		return err
	}

	// t.LastLogIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LastLogIndex)); err != nil {
		return err
	}

	// t.LastLogTerm (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LastLogTerm)); err != nil {
		return err
	}

	// t.LeadershipTransfer (bool) (bool)
	if err := cbg.WriteBool(w, t.LeadershipTransfer); err != nil {
		return err
	}
	return nil
}

func (t *RequestVoteRequest) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RequestVoteRequest{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.Candidate ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Candidate: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Candidate = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Candidate); err != nil {
		return err
	}

	// t.LastLogIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LastLogIndex = uint64(extra)

	}
	// t.LastLogTerm (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LastLogTerm = uint64(extra)

	}
	// t.LeadershipTransfer (bool) (bool)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.LeadershipTransfer = false
	case 21:
		t.LeadershipTransfer = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufRequestVoteResponse = []byte{132}

func (t *RequestVoteResponse) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufRequestVoteResponse); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.Peers ([]uint8) (slice)
	if len(t.Peers) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Peers was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Peers))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Peers); err != nil {
		return err
	}

	// t.Granted (bool) (bool)
	if err := cbg.WriteBool(w, t.Granted); err != nil {
		return err
	}
	return nil
}

func (t *RequestVoteResponse) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RequestVoteResponse{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.Peers ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Peers: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Peers = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Peers); err != nil {
		return err
	}

	// t.Granted (bool) (bool)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.Granted = false
	case 21:
		t.Granted = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufRequestPreVoteRequest = []byte{132}

func (t *RequestPreVoteRequest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufRequestPreVoteRequest); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.LastLogIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LastLogIndex)); err != nil {
		return err
	}

	// t.LastLogTerm (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LastLogTerm)); err != nil {
		return err
	}

	return nil
}

func (t *RequestPreVoteRequest) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RequestPreVoteRequest{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.LastLogIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LastLogIndex = uint64(extra)

	}
	// t.LastLogTerm (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LastLogTerm = uint64(extra)

	}
	return nil
}

var lengthBufRequestPreVoteResponse = []byte{131}

func (t *RequestPreVoteResponse) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufRequestPreVoteResponse); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.Granted (bool) (bool)
	if err := cbg.WriteBool(w, t.Granted); err != nil {
		return err
	}
	return nil
}

func (t *RequestPreVoteResponse) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RequestPreVoteResponse{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.Granted (bool) (bool)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.Granted = false
	case 21:
		t.Granted = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufInstallSnapshotRequest = []byte{138}

func (t *InstallSnapshotRequest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufInstallSnapshotRequest); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.SnapshotVersion (raft.SnapshotVersion) (int64)
	if t.SnapshotVersion >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.SnapshotVersion)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.SnapshotVersion-1)); err != nil {
			return err
		}
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.Leader ([]uint8) (slice)
	if len(t.Leader) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Leader was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Leader))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Leader); err != nil {
		return err
	}

	// t.LastLogIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LastLogIndex)); err != nil {
		return err
	}

	// t.LastLogTerm (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LastLogTerm)); err != nil {
		return err
	}

	// t.Peers ([]uint8) (slice)
	if len(t.Peers) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Peers was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Peers))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Peers); err != nil {
		return err
	}

	// t.Configuration ([]uint8) (slice)
	if len(t.Configuration) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Configuration was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Configuration))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Configuration); err != nil {
		return err
	}

	// t.ConfigurationIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.ConfigurationIndex)); err != nil {
		return err
	}

	// t.Size (int64) (int64)
	if t.Size >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Size)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.Size-1)); err != nil {
			return err
		}
	}

	return nil
}

func (t *InstallSnapshotRequest) UnmarshalCBOR(r io.Reader) (err error) {
	*t = InstallSnapshotRequest{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 10 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.SnapshotVersion (raft.SnapshotVersion) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.SnapshotVersion = SnapshotVersion(extraI)
	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.Leader ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Leader: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Leader = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Leader); err != nil {
		return err
	}

	// t.LastLogIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LastLogIndex = uint64(extra)

	}
	// t.LastLogTerm (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LastLogTerm = uint64(extra)

	}
	// t.Peers ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Peers: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Peers = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Peers); err != nil {
		return err
	}

	// t.Configuration ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Configuration: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Configuration = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Configuration); err != nil {
		return err
	}

	// t.ConfigurationIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.ConfigurationIndex = uint64(extra)

	}
	// t.Size (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Size = int64(extraI)
	}
	return nil
}

var lengthBufInstallSnapshotResponse = []byte{131}

func (t *InstallSnapshotResponse) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufInstallSnapshotResponse); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.Success (bool) (bool)
	if err := cbg.WriteBool(w, t.Success); err != nil {
		return err
	}
	return nil
}

func (t *InstallSnapshotResponse) UnmarshalCBOR(r io.Reader) (err error) {
	*t = InstallSnapshotResponse{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.Success (bool) (bool)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.Success = false
	case 21:
		t.Success = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufTimeoutNowRequest = []byte{129}

func (t *TimeoutNowRequest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufTimeoutNowRequest); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *TimeoutNowRequest) UnmarshalCBOR(r io.Reader) (err error) {
	*t = TimeoutNowRequest{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	return nil
}

var lengthBufTimeoutNowResponse = []byte{129}

func (t *TimeoutNowResponse) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufTimeoutNowResponse); err != nil {
		return err
	}

	// t.RPCHeader (raft.RPCHeader) (struct)
	if err := t.RPCHeader.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *TimeoutNowResponse) UnmarshalCBOR(r io.Reader) (err error) {
	*t = TimeoutNowResponse{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RPCHeader (raft.RPCHeader) (struct)

	{

		if err := t.RPCHeader.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RPCHeader: %w", err)
		}

	}
	return nil
}

var lengthBufRPCHeader = []byte{131}

func (t *RPCHeader) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufRPCHeader); err != nil {
		return err
	}

	// t.ProtocolVersion (raft.ProtocolVersion) (int64)
	if t.ProtocolVersion >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.ProtocolVersion)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.ProtocolVersion-1)); err != nil {
			return err
		}
	}

	// t.ID ([]uint8) (slice)
	if len(t.ID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.ID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.ID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.ID); err != nil {
		return err
	}

	// t.Addr ([]uint8) (slice)
	if len(t.Addr) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Addr was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Addr))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Addr); err != nil {
		return err
	}

	return nil
}

func (t *RPCHeader) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RPCHeader{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.ProtocolVersion (raft.ProtocolVersion) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.ProtocolVersion = ProtocolVersion(extraI)
	}
	// t.ID ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.ID: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.ID = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.ID); err != nil {
		return err
	}

	// t.Addr ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Addr: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Addr = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Addr); err != nil {
		return err
	}

	return nil
}

var lengthBufLog = []byte{134}

func (t *Log) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufLog); err != nil {
		return err
	}

	// t.Index (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Index)); err != nil {
		return err
	}

	// t.Term (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Term)); err != nil {
		return err
	}

	// t.Type (raft.LogType) (uint8)
	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Type)); err != nil {
		return err
	}

	// t.Data ([]uint8) (slice)
	if len(t.Data) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Data was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Data))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Data); err != nil {
		return err
	}

	// t.Extensions ([]uint8) (slice)
	if len(t.Extensions) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Extensions was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Extensions))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Extensions); err != nil {
		return err
	}

	// t.AppendedAt (time.Time) (struct)
	if err := TimeMarshalCBOR(&t.AppendedAt, cw); err != nil {
		return err
	}
	return nil
}

func (t *Log) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Log{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Index (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Index = uint64(extra)

	}
	// t.Term (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Term = uint64(extra)

	}
	// t.Type (raft.LogType) (uint8)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajUnsignedInt {
		return fmt.Errorf("wrong type for uint8 field")
	}
	if extra > math.MaxUint8 {
		return fmt.Errorf("integer in input was too large for uint8 field")
	}
	t.Type = LogType(extra)
	// t.Data ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Data: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Data = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Data); err != nil {
		return err
	}

	// t.Extensions ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Extensions: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Extensions = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Extensions); err != nil {
		return err
	}

	// t.AppendedAt (time.Time) (struct)

	{

		if err := TimeUnmarshalCBOR(&t.AppendedAt, cr); err != nil {
			return xerrors.Errorf("unmarshaling t.AppendedAt: %w", err)
		}

	}
	return nil
}

var lengthBufTimeBytes = []byte{129}

func (t *TimeBytes) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufTimeBytes); err != nil {
		return err
	}

	// t.Bytes ([]uint8) (slice)
	if len(t.Bytes) > 16 {
		return xerrors.Errorf("Byte array in field t.Bytes was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Bytes))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Bytes); err != nil {
		return err
	}

	return nil
}

func (t *TimeBytes) UnmarshalCBOR(r io.Reader) (err error) {
	*t = TimeBytes{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Bytes ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 16 {
		return fmt.Errorf("t.Bytes: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Bytes = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Bytes); err != nil {
		return err
	}

	return nil
}

var lengthBufString = []byte{129}

func (t *String) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufString); err != nil {
		return err
	}

	// t.Value (string) (string)
	if len(t.Value) > 8192 {
		return xerrors.Errorf("Value in field t.Value was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Value))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Value)); err != nil {
		return err
	}
	return nil
}

func (t *String) UnmarshalCBOR(r io.Reader) (err error) {
	*t = String{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Value (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.Value = string(sval)
	}
	return nil
}
