// Code generated by mog. DO NOT EDIT.

package transportv1

import "github.com/hashicorp/raft"

func LogToStruct(s *Log, t *raft.Log) {
	if s == nil {
		return
	}
	t.Index = s.Index
	t.Term = s.Term
	t.Type = raft.LogType(s.Type)
	t.Data = s.Data
	t.Extensions = s.Extensions
	t.AppendedAt = TimeFromProto(s.AppendedAt)
}
func LogFromStruct(t *raft.Log, s *Log) {
	if s == nil {
		return
	}
	s.Index = t.Index
	s.Term = t.Term
	s.Type = uint32(t.Type)
	s.Data = t.Data
	s.Extensions = t.Extensions
	s.AppendedAt = TimeToProto(t.AppendedAt)
}
func RPCHeaderToStruct(s *RPCHeader, t *raft.RPCHeader) {
	if s == nil {
		return
	}
	t.ProtocolVersion = raft.ProtocolVersion(s.ProtocolVersion)
	t.ID = s.Id
	t.Addr = s.Addr
}
func RPCHeaderFromStruct(t *raft.RPCHeader, s *RPCHeader) {
	if s == nil {
		return
	}
	s.ProtocolVersion = int32(t.ProtocolVersion)
	s.Id = t.ID
	s.Addr = t.Addr
}
